[project]
name = "veracity"
description = "HDL verification library for software models"
version = "1.0.0"
requires-python = ">=3.7"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"